### PR TITLE
Add docker build script

### PR DESCRIPTION
**Pull request by PythonCoderAS**

### CODE REVIEW

**Review by vosmiic — APPROVED** [review]
Thanks for the PR, I personally haven't used github workflows before so I can't tell comment much on the yml file but have tested the docker build and all seems good. This will make building the plugin much easier, again thanks for the contribution

**Comment by vosmiic** [comment]
Hey @PythonCoderAS any chance that you could look into why the ARM docker build is failing? I have tried to diagnose the issues but everything seems to work locally perfectly fine. I don't think it helps that my knowledge of github workflows is low. No worries if you haven't got the time, the X86 builds are still passing luckily which I would presume are more popular. Thanks

**Comment by PythonCoderAS** [comment]
> Hey @PythonCoderAS any chance that you could look into why the ARM docker build is failing? I have tried to diagnose the issues but everything seems to work locally perfectly fine. I don't think it helps that my knowledge of github workflows is low. No worries if you haven't got the time, the X86 builds are still passing luckily which I would presume are more popular. Thanks

I have no idea why it's failing, the weirdest part is that it's intermittently failing.

**Comment by vosmiic** [comment]
Yeah its odd. I'll have a proper look at it when I get a chance.

**Pull request merged**
