### PR TITLE
Fix Shikimori provider issues

### LINKED ISSUE #107: Shikimori provider resets score
**Describe the bug**

Shikimori series score is reset on update.

**Logs**

```
[2024-02-29 11:40:39.973 +03:00] [INF] [10] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime reference found in anime list XML
[2024-02-29 11:40:39.974 +03:00] [INF] [10] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[2024-02-29 11:40:40.450 +03:00] [INF] [10] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[2024-02-29 11:40:40.451 +03:00] [INF] [10] jellyfin_ani_sync.UpdateProviderStatus: Using provider Shikimori...
[2024-02-29 11:40:51.409 +03:00] [INF] [11] jellyfin_ani_sync.UpdateProviderStatus: (Shikimori) Found matching series: Ishura
[2024-02-29 11:40:51.782 +03:00] [INF] [11] jellyfin_ani_sync.UpdateProviderStatus: (Shikimori) Series (Ishura) found on watching list
[2024-02-29 11:40:53.176 +03:00] [INF] [11] jellyfin_ani_sync.UpdateProviderStatus: (Shikimori) Updated series (Ishura) progress to 9
```

**To Reproduce**

1. Set a score for a title on Watching list.
2. Watch next episode in Jellyfin.

**Expected behavior**

Score does not change on series progress or status update.

**Screenshots**

image

**Desktop:**
 - Browser n/a
 - Jellyfin version 10.8.13
 - Plugin version 3.0

### LINKED ISSUE #110: NPE during status update with Shikimori provider
**Describe the bug**

NPE during status update with Shikimori provider.

**Logs**

```
[2024-03-03 22:00:13.766 +03:00] [INF] [149] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime reference found in anime list XML
[2024-03-03 22:00:13.766 +03:00] [INF] [149] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[2024-03-03 22:00:14.466 +03:00] [INF] [208] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[2024-03-03 22:00:14.466 +03:00] [INF] [208] jellyfin_ani_sync.UpdateProviderStatus: Using provider Shikimori...
[2024-03-03 22:00:28.544 +03:00] [ERR] [208] jellyfin_ani_sync.SessionServerEntry: Fatal error occured during anime sync job: System.NullReferenceException: Object reference not set to an instance of an object.
   at jellyfin_ani_sync.UpdateProviderStatus.TitleCheck(Anime anime, Episode episode, Movie movie)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
```

**To Reproduce**

n/a

**Expected behavior**

The plugin successfully updates progress via Shikimori API.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - Browser n/a
 - Jellyfin version 10.8.13
 - Plugin version 3.0

**Additional context**

I’d assume that is because `Anime` instance is not fully initialized from the available Shikimori data,

https://github.com/vosmiic/jellyfin-ani-sync/blob/de2c88303a6594af8f3acac4f059755e48171d08/Helpers/ClassConversions.cs#L97-L102

https://github.com/vosmiic/jellyfin-ani-sync/blob/de2c88303a6594af8f3acac4f059755e48171d08/UpdateProviderStatus.cs#L341-L347

https://github.com/vosmiic/jellyfin-ani-sync/blob/de2c88303a6594af8f3acac4f059755e48171d08/Models/Shikimori/ShikimoriMedia.cs#L7-L21

Here is a response from https://shikimori.one/api/animes/52299 with most of the fields omitted except for those that should be used for title check:
```json
{
  "id": 52299,
  "myanimelist_id": 52299,
  "name": "Ore dake Level Up na Ken",
  "russian": "Поднятие уровня в одиночку",
  "english": [ "Solo Leveling" ],
  "japanese": [ "俺 だ け レ ベ ル ア ッ プ な 件 " ],
  "synonyms": [
    "I Level Up Alone",
    "Na Honjaman Level Up"
  ]
}
```

Also note that strings may be `null`, e.g. https://shikimori.one/api/animes/54873

```json
{
  "id": 54873,
  "myanimelist_id": 54873,
  "name": "Takoru TV",
  "russian": "Такору",
  "english": [
    null
  ],
  "japanese": [
    "た こ る TV"
  ],
  "synonyms": []
}
```

### PR DESCRIPTION
**Pull request by tie**
Fixes #107, fixes #110

### CODE REVIEW

**Comment by tie** [comment]
#110 can be fixed more efficiently with Shikimori GraphQL API. I've marked the PR as a draft for now until I implement this.

**Comment by tie** [comment]
I haven’t verified rewatching and adding new titles to the watching list, but otherwise seems to be working fine.
https://shikimori.one/Nia+Teppelin/history/logs

Note though that the implementation in this PR currently does not use `GraphQlHelper` class. It had some limitations that I wanted to avoid refactoring to move forward with the fix (e.g. no error handling).

**Comment by vosmiic** [comment]
Thanks for this PR, using GraphQL is pretty much always better in terms of efficiency so these changes are great.
I have changed the Shikimori unit tests to reflect these changes and they are all passing now.

Any reason for removing the JSON converter functionality? I think the only reason to keep certain fields like ID as `string` is because it only accepts `string`'s, and the actual ID is always an `int` (I believe, I could be wrong though). I feel like its better to natively treat it as an `int`, so there is no confusion on what the actual data type is. I'm fully open to removing it though if you think its better practice.

**Comment by tie** [comment]
I feel like IDs being integers is an implementation detail. There are no operations that actually rely IDs being integers, API returns and accepts them as strings, and keeping them as strings throughout the plugin code makes the code a bit more flexible in terms of providers that can be supported (not all APIs use sequential integers for IDs, e.g. it is also common to have UUID strings).

**Review by vosmiic — APPROVED** [review]

**Pull request merged**
