### PR TITLE
Search for Anibd id within Season

### PR DESCRIPTION
**Pull request by Hitsounds**
Anidb has no concept of series, each season has a unique id, therefore the plugin should look for an id for each season. 

This also makes the plugin play nicely with [Shokofin](https://github.com/ShokoAnime/Shokofin).

### CODE REVIEW

**Comment by Hitsounds** [comment]
Yes, I have shokofin provide anidb ids at the season level as each season has a unique anidb id.

The current behaviour only ever matches the anidb id for the first season (which works well for single-season anime) however falls back to tvdb ids and title searching for any other seasons. 

With the PR you should get the following cases:

Case 1: You have anidb ids provided at season level
- Improved matching as anidb id of season can be directly fetched

Case 2: You don't have anidb ids provided at season level
- For seasons > 1 will fall back to other sources as is current behaviour
- For season = 1 will use other sources whereas current behaviour is to assume anidb id set at series level is the id for the 1st season

**Comment by vosmiic** [comment]
>The current behaviour only ever matches the anidb id for the first season (which works well for single-season anime) however falls back to tvdb ids and title searching for any other seasons.

Yeah, I think this could be improved if we lookup the AniDB ID in the anime XML file, and if the user is watching the first season then instantly return the results, if not then we could lookup the other seasons by using the TVDB ID. 
I'll add it to my list of things to implement.

>We could also have it resort back to looking for an anidb id at the series level if none is found at the season level but I feel that this does not reflect how anidb's data is structured and so should be discouraged rather than supported.

I agree, it should be at the season level as you have it setup, but we would need to request metadata providers and/or Jellyfin change the way it is handled which probably will not happen.
I think the way we handle it at the moment works, but checking at season level shouldn't negatively impact anything so maybe change it so we check at both the season (first) and series levels?

**Comment by Nalsai** [comment]
Adding support for anidbid at the season level in [jellyfin-plugin-anidb](https://github.com/jellyfin/jellyfin-plugin-anidb) should not be a problem.

Although, I would argue that AniDB has no concept of seasons (rather than no concept of series) - each season is a different show

Normally seasons don't have names (they are usually just named Season 1, Season 2,...). Therefore they can't be used to search for the anime in AniDB by jellyfin-plugin-anidb. Although it is possible to implement, if users name their folders appropriately, I think.

Using the id in the season and falling back to the id in the show is a good idea in my opinion -> are there any disadvantages?

**Comment by vosmiic** [comment]
>Adding support for anidbid at the season level in jellyfin-plugin-anidb should not be a problem.

I might look at implementing it and creating a PR - but at the moment pretty much all of my spare time is being spent working on this project, so it probably won't be any time soon.

>Although, I would argue that AniDB has no concept of seasons (rather than no concept of series) - each season is a different show

Yeah I can understand why it would be set at series level instead of at the season level. But I can also understand the argument that it should be at season level.

>Using the id in the season and falling back to the id in the show is a good idea in my opinion -> are there any disadvantages/problems?

Yep I think supporting both is a good idea - just waiting to see if @Hitsounds has any arguments against it.

**Comment by Hitsounds** [comment]
Sorry for the delay.

Supporting both seems to be the best of both worlds and I have made the necessary changes. 

I also added a bug fix for rare cases when the latest xml file is smaller than the one on disk: https://github.com/vosmiic/jellyfin-ani-sync/pull/30/commits/a4463231a5ad5244ad82c9ad7b9b279abb140c8f

**Review by vosmiic — APPROVED** [review]
This looks good, thanks for adding the anime list fix as well.
Unfortunately this probably won't be in a release for quite a while as I don't yet have enough changes to justify a new version, but if you would like to use the new functionality now I would advise building it (or I can for you, if you would prefer) and overwriting the plugin dll file on your server.
Thanks again for the PR!

**Pull request merged**
