### PR TITLE
Add NSFW param to MAL API calls

### LINKED ISSUE #94: NSFW Anime Support
**Describe the bug**
MAL will not return anime information for NSFW anime if the NSFW parameter is not provided

**Logs**
```
[2023-12-27 14:42:03.264 +00:00] [WRN] [71] jellyfin_ani_sync.UpdateProviderStatus: Did not get provider IDs, defaulting to episode provided AniList ID
[2023-12-27 14:42:03.265 +00:00] [INF] [71] jellyfin_ani_sync.UpdateProviderStatus: Using provider Mal...
[2023-12-27 14:42:03.265 +00:00] [INF] [71] jellyfin_ani_sync.Api.MalApiCalls: Starting search for anime (GET https://api.myanimelist.net/v2/anime?q=InterspeciesReviewers&fields=id%2Ctitle%2Calternative_titles%2Cnum_episodes%2Cstatus)...
[2023-12-27 14:42:03.683 +00:00] [INF] [53] jellyfin_ani_sync.Api.MalApiCalls: Search complete
[2023-12-27 14:42:03.684 +00:00] [WRN] [53] jellyfin_ani_sync.UpdateProviderStatus: (Mal) Series not found
```

**To Reproduce**
1. Add NSFW anime to Jellyfin with Anilist ID
2. Watch episode

**Expected behavior**
The anime should be found and added

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser [e.g. firefox, chrome] Chrome
 - Jellyfin version [e.g. 10.8] 10.8.13
 - Plugin version [e.g. 2.9] 2.9

**Additional context**
The URL in logs return this:

```json
{
  "data": [
    {
      "node": {
        "id": 31149,
        "title": "Persona 3 the Movie 4: Winter of Rebirth",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/9/77828.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/9/77828l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Persona 3 the Movie: #4 Winter of Rebirth",
          "ja": "PERSONA3 THE MOVIE —#4 Winter of Rebirth—"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 33988,
        "title": "Demi-chan wa Kataritai",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/8/83417.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/8/83417l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Ajin-chan wa Kataritai"
          ],
          "en": "Interviews With Monster Girls",
          "ja": "亜人ちゃんは語りたい"
        },
        "num_episodes": 12,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 731,
        "title": "Interstella5555: The 5tory of The 5ecret 5tar 5ystem",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/5/82786.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/5/82786l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Interstellar 5555"
          ],
          "en": "",
          "ja": "インターステラ5555"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 35823,
        "title": "Demi-chan wa Kataritai: Demi-chan no Natsuyasumi",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/6/88769.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/6/88769l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Demi-chan wa Kataritai Episode 13"
          ],
          "en": "Interviews With Monster Girls: The Demi-chans' Summer Break",
          "ja": "亜人ちゃんは語りたい 亜人ちゃんの夏休み"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 1170,
        "title": "Slayers Specials",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1372/92532.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1372/92532l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Slayers Special OVA"
          ],
          "en": "Slayers: The Book of Spells",
          "ja": "スレイヤーズすぺしゃる"
        },
        "num_episodes": 3,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 37277,
        "title": "Beatless Intermission",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1709/90468.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1709/90468l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Beatless Recap",
            "Beatless Episode 5.5",
            "Beatless Episode 9.5",
            "Beatless Episode 14.5",
            "Beatless Episode 16.5"
          ],
          "en": "",
          "ja": "BEATLESS Intermission"
        },
        "num_episodes": 4,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 495,
        "title": "Bakuretsu Hunters",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1607/96463.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1607/96463l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Spell Wars: Sorcerer Hunters Revenge"
          ],
          "en": "Sorcerer Hunters",
          "ja": "爆れつハンター"
        },
        "num_episodes": 26,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 40272,
        "title": "A3! Season Autumn & Winter",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1049/108197.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1049/108197l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Act! Addict! Actors! Season Autumn & Winter"
          ],
          "en": "A3! Season Autumn & Winter",
          "ja": "A3! SEASON AUTUMN & WINTER"
        },
        "num_episodes": 12,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 33032,
        "title": "Drifters: Special Edition",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1141/97770.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1141/97770l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Drifters OVA"
          ],
          "en": "",
          "ja": "DRIFTERS Special edition"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    }
  ],
  "paging": {
    "next": "https://api.myanimelist.net/v2/anime?offset=10&q=InterspeciesReviewers&fields=id%2Ctitle%2Calternative_titles%2Cnum_episodes%2Cstatus"
  }
}
```

This URL: https://api.myanimelist.net/v2/anime?q=InterspeciesReviewers&fields=id%2Ctitle%2Calternative_titles%2Cnum_episodes%2Cstatus&nsfw=true returns this:

```json
{
  "data": [
    {
      "node": {
        "id": 40010,
        "title": "Ishuzoku Reviewers",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1870/105970.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1870/105970l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Interspecies Reviewers",
          "ja": "異種族レビュアーズ"
        },
        "num_episodes": 12,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 31149,
        "title": "Persona 3 the Movie 4: Winter of Rebirth",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/9/77828.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/9/77828l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Persona 3 the Movie: #4 Winter of Rebirth",
          "ja": "PERSONA3 THE MOVIE —#4 Winter of Rebirth—"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 33988,
        "title": "Demi-chan wa Kataritai",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/8/83417.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/8/83417l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Ajin-chan wa Kataritai"
          ],
          "en": "Interviews With Monster Girls",
          "ja": "亜人ちゃんは語りたい"
        },
        "num_episodes": 12,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 731,
        "title": "Interstella5555: The 5tory of The 5ecret 5tar 5ystem",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/5/82786.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/5/82786l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Interstellar 5555"
          ],
          "en": "",
          "ja": "インターステラ5555"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 35823,
        "title": "Demi-chan wa Kataritai: Demi-chan no Natsuyasumi",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/6/88769.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/6/88769l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Demi-chan wa Kataritai Episode 13"
          ],
          "en": "Interviews With Monster Girls: The Demi-chans' Summer Break",
          "ja": "亜人ちゃんは語りたい 亜人ちゃんの夏休み"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 1170,
        "title": "Slayers Specials",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1372/92532.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1372/92532l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Slayers Special OVA"
          ],
          "en": "Slayers: The Book of Spells",
          "ja": "スレイヤーズすぺしゃる"
        },
        "num_episodes": 3,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 37277,
        "title": "Beatless Intermission",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1709/90468.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1709/90468l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Beatless Recap",
            "Beatless Episode 5.5",
            "Beatless Episode 9.5",
            "Beatless Episode 14.5",
            "Beatless Episode 16.5"
          ],
          "en": "",
          "ja": "BEATLESS Intermission"
        },
        "num_episodes": 4,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 495,
        "title": "Bakuretsu Hunters",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1607/96463.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1607/96463l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Spell Wars: Sorcerer Hunters Revenge"
          ],
          "en": "Sorcerer Hunters",
          "ja": "爆れつハンター"
        },
        "num_episodes": 26,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 40272,
        "title": "A3! Season Autumn & Winter",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1049/108197.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1049/108197l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Act! Addict! Actors! Season Autumn & Winter"
          ],
          "en": "A3! Season Autumn & Winter",
          "ja": "A3! SEASON AUTUMN & WINTER"
        },
        "num_episodes": 12,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 33032,
        "title": "Drifters: Special Edition",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1141/97770.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1141/97770l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Drifters OVA"
          ],
          "en": "",
          "ja": "DRIFTERS Special edition"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    }
  ],
  "paging": {
    "next": "https://api.myanimelist.net/v2/anime?offset=10&q=InterspeciesReviewers&fields=id%2Ctitle%2Calternative_titles%2Cnum_episodes%2Cstatus&nsfw=true"
  }
}
```

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Fix #94

### CODE REVIEW

**Comment by vosmiic** [comment]
Thanks for the PR, but I think it needs some extensions. First we would need to make sure the other providers support operating on NSFW content and I would prefer if there were a switch to allow or disallow updating NSFW content.
I'll work on the above changes soon, got quite a lot to catch up on.

**Comment by PythonCoderAS** [comment]
> Thanks for the PR, but I think it needs some extensions. First we would need to make sure the other providers support operating on NSFW content and I would prefer if there were a switch to allow or disallow updating NSFW content. I'll work on the above changes soon, got quite a lot to catch up on.

With regards to NSFW, I know Anilist supports it (with a setting that has to be enabled somewhere in the settings), Kitsu does not, and Simkl supports some level (I see Redo of healer but no H-anime).

**Comment by vosmiic** [comment]
I think that should be good to go, could you confirm that this is working? I can't test it with my local library

**Comment by PythonCoderAS** [comment]
> I think that should be good to go, could you confirm that this is working? I can't test it with my local library

How do I install this into my Jellyfin?

**Comment by vosmiic** [comment]
You can [build](https://github.com/vosmiic/jellyfin-ani-sync#build) it if you are able to and then follow the [manual install](https://github.com/vosmiic/jellyfin-ani-sync#manual) instructions (but use the built dll file, not one from releases). If you can't build it I can send you a dll file.

**Review by vosmiic — APPROVED** [review]
All looks good, just waiting for the go-ahead from you after you have tested it (if you are able to)

**Comment by PythonCoderAS** [comment]
> All looks good, just waiting for the go-ahead from you after you have tested it (if you are able to)

I tested it but I'm still getting the error:

```
[2024-01-14 20:36:21.573 +00:00] [WRN] [76] jellyfin_ani_sync.UpdateProviderStatus: Did not get provider IDs, defaulting to episode provided AniList ID
[2024-01-14 20:36:21.577 +00:00] [INF] [76] jellyfin_ani_sync.UpdateProviderStatus: Using provider Mal...
[2024-01-14 20:36:21.626 +00:00] [INF] [76] jellyfin_ani_sync.Api.MalApiCalls: Starting search for anime (GET https://api.myanimelist.net/v2/anime?q=SweetPunishment&nsfw=true&fields=id%2Ctitle%2Calternative_titles%2Cnum_episodes%2Cstatus)...
[2024-01-14 20:36:22.022 +00:00] [INF] [76] jellyfin_ani_sync.Api.MalApiCalls: Search complete
[2024-01-14 20:36:22.027 +00:00] [WRN] [76] jellyfin_ani_sync.UpdateProviderStatus: (Mal) Series not found
```

The URL is not the problem, however, as this is the JSON I got back:

```json
{
  "data": [
    {
      "node": {
        "id": 37440,
        "title": "Psycho-Pass: Sinners of the System Case.1 - Tsumi to Batsu",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1623/96878.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1623/96878l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Psycho-Pass SS Case 1: Tsumi to Batsu"
          ],
          "en": "Psycho-Pass: Sinners of the System Case.1 - Crime and Punishment",
          "ja": "PSYCHO-PASS サイコパス|SS(Sinners of the System) Case.1「罪と罰」"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 37320,
        "title": "Amai Choubatsu: Watashi wa Kanshu Senyou Pet",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1464/108630.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1464/108630l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Amai Choubatsu: Watashi wa Kanshu Sen'you Pet"
          ],
          "en": "Sweet Punishment: I'm the Guard's Personal Pet",
          "ja": "甘い懲罰~私は看守専用ペット"
        },
        "num_episodes": 13,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 30460,
        "title": "Kanojo ga Nekomimi ni Kigaetara",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1767/119772.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1767/119772l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Cat Play Punishment",
          "ja": "彼女がネコミミに着替えたら"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 3382,
        "title": "Korashime",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/7/7431.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/7/7431l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Punishment",
          "ja": "懲らしめ"
        },
        "num_episodes": 2,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 56009,
        "title": "Yuusha-kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1377/137193.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1377/137193l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Punishment for Brave Hero: 9004 Corps Prison Record, Sentenced to Hero Punishment: The Service Records of the 9004th Penitent Hero Corps",
            "Hero Punishment"
          ],
          "en": "Sentenced to Brave Punishment",
          "ja": "勇者刑に処す 懲罰勇者9004隊刑務記録"
        },
        "num_episodes": 0,
        "status": "not_yet_aired"
      }
    },
    {
      "node": {
        "id": 25457,
        "title": "Avengers Confidential: Black Widow to Punisher",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/10/66947.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/10/66947l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Marvel Avengers Confidential: Black Widow & Punisher",
          "ja": "アベンジャーズ コンフィデンシャル: ブラックウィドウとパニッシャー"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 14175,
        "title": "Hanasaku Iroha Movie: Home Sweet Home",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/9/70701.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/9/70701l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Hanasaku Iroha: Home Sweet Home"
          ],
          "en": "Hanasaku Iroha the Movie: Home Sweet Home",
          "ja": "劇場版 花咲くいろは HOME SWEET HOME"
        },
        "num_episodes": 1,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 36864,
        "title": "Akkun to Kanojo",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/1404/90601.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/1404/90601l.jpg"
        },
        "alternative_titles": {
          "synonyms": [
            "Akkun and His Girlfriend"
          ],
          "en": "My Sweet Tyrant",
          "ja": "あっくんとカノジョ"
        },
        "num_episodes": 25,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 2325,
        "title": "Angel Blade Punish!",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/5/3662.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/5/3662l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "",
          "ja": "エンジェルブレイドパニッシュ！"
        },
        "num_episodes": 3,
        "status": "finished_airing"
      }
    },
    {
      "node": {
        "id": 32828,
        "title": "Amaama to Inazuma",
        "main_picture": {
          "medium": "https://cdn.myanimelist.net/images/anime/6/80546.jpg",
          "large": "https://cdn.myanimelist.net/images/anime/6/80546l.jpg"
        },
        "alternative_titles": {
          "synonyms": [],
          "en": "Sweetness & Lightning",
          "ja": "甘々と稲妻"
        },
        "num_episodes": 12,
        "status": "finished_airing"
      }
    }
  ],
  "paging": {
    "next": "https://api.myanimelist.net/v2/anime?offset=10&q=SweetPunishment&nsfw=true&fields=id%2Ctitle%2Calternative_titles%2Cnum_episodes%2Cstatus"
  }
}
```

The correct entry is the second item in the search, but it didn't find it for some reason. The Anilist ID assigned is 101160 which does have the MAL ID:

```json
{
  "data": {
    "Media": {
      "id": 101160,
      "idMal": 37320
    }
  }
}
```

**Comment by vosmiic** [comment]
That is because the plugin is falling back to the traditional method of searching via the API, which does a basic title match to detect the anime instead of using the metadata. Normally this would be fixed by using the TVDB metadata provider, but the anime list XML file seems to not contain the entry so it won't help in this case.

Is the Anilist metadata provider supplying that MAL ID? If so, we could use that to map to the other providers (and of course to MAL).

**Comment by PythonCoderAS** [comment]
> That is because the plugin is falling back to the traditional method of searching via the API, which does a basic title match to detect the anime instead of using the metadata. Normally this would be fixed by using the TVDB metadata provider, but the anime list XML file seems to not contain the entry so it won't help in this case.
> 
> Is the Anilist metadata provider supplying that MAL ID? If so, we could use that to map to the other providers (and of course to MAL).

Anilist _specifically_ has a mapping to MyAnimeList only. Kitsu has [mappings](https://kitsu.docs.apiary.io/#reference/media-relations/mappings/fetch-collection) to at least these ones (not guaranteed to exist but these are possible known values) and more that aren't documented (I saw Trakt and a bunch of others as well):
Screenshot 2024-01-14 at 7 26 08 PM

Kitsu in particular will not show mature content without being logged in and the user needs to enable it in their settings.

**Comment by vosmiic** [comment]
> Anilist _specifically_ has a mapping to MyAnimeList only. Kitsu has [mappings](https://kitsu.docs.apiary.io/#reference/media-relations/mappings/fetch-collection) to at least these ones (not guaranteed to exist but these are possible known values) and more that aren't documented (I saw Trakt and a bunch of others as well): Screenshot 2024-01-14 at 7 26 08 PM
> 
> Kitsu in particular will not show mature content without being logged in and the user needs to enable it in their settings.

Ah I thought it might have added it to the metadata list when using Anilist as the main metadata provider. Yeah I have seen that the MAL ID is returned by the Anilist API, but I don't think using resources from one provider API to feed into another API is a good idea, as a few API's simply disallow this.

**Pull request merged**
